qa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

from qaapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('qaapp.urls', namespace='qa')),
]

handler404 = views.handler404

qaapp/urls.py
from django.urls import path

from qaapp.views import QuestionDetailsView
from . import views

app_name = 'qa'

urlpatterns = [
    path('', views.QuestionListView.as_view(), name='home'),
    path('questions/<slug:slug>/', QuestionDetailsView.as_view(), name='questions-detail'),
    path('questions/create', views.QuestionCreateView.as_view(), name='questions-create'),
    path('questions/<slug:slug>/edit', views.QuestionUpdateView.as_view(), name='questions-edit'),
    path('questions/<slug:slug>/delete', views.QuestionDestroyView.as_view(), name='questions-delete'),
    path('questions/<int:question_id>/<str:flag>', views.question_vote, name='questions-vote'),
    # answer
    path('answers/<int:question_id>/<int:answer_id>/best_answer', views.mark_as_best, name='mark-as-best'),
]

templates/answers/_create.html
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h3>Your Answer</h3>
                </div>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
{#                            <label for="id_{{ field.name }}">{{ field.label }}</label>#}
                            {{ field }}
                        </div>
                    {% endfor %}
                    {#                    <div class="form-group">#}
                    {#                        <textarea class="form-control" rows="7"#}
                    {#                                  name="body"></textarea>#}
                    {#                        <div class="invalid-feedback">#}
                    {#                            <strong></strong>#}
                    {#                        </div>#}
                    {#                    </div>#}
                    <div class="form-group">
                        <button type="submit" class="btn btn-lg btn-outline-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/answers/_index.html
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h2>{{ answers.count }} answers</h2>
                </div>
                <hr>

                {% for answer in answers %}
                    <div class="media">
                        <div class="d-fex flex-column vote-controls">
{#                            <a title="This answer is useful"#}
{#                               class="vote-up">#}
{#                                <i class="fas fa-caret-up fa-3x"></i>#}
{#                            </a>#}
{#                            <form id="up-vote-answer"#}
{#                                  action="/answers/" method="POST" style="display:none;">#}
{#                                <input type="hidden" name="vote" value="1">#}
{#                            </form>#}
{##}
{#                            <span class="votes-count">2</span>#}
{##}
{#                            <a title="This answer is not useful"#}
{#                               class="vote-down">#}
{#                                <i class="fas fa-caret-down fa-3x"></i>#}
{#                            </a>#}
{#                            <form id="down-vote-answer-"#}
{#                                  action="/answers//vote" method="POST" style="display:none;">#}
{#                                <input type="hidden" name="vote" value="-1">#}
{#                            </form>#}
                            {% if request.user == question.user and question.best_answer_id == null %}
                            <a title="Mark this answer as best answer" class="mt-2"
                               onclick="event.preventDefault(); document.getElementById('accept-answer-{{ answer.id }}').submit();"
                            >
                                <i class="fas fa-check fa-2x"></i>
                            </a>
                            <form action="{% url 'qa:mark-as-best' question.id answer.id %}" id="accept-answer-{{ answer.id }}" method="post" style="display: none">
                            {% csrf_token %}
                            </form>
                            {% endif %}
                            {% if question.best_answer_id == answer.id %}
                                <a style="color: yellow;" title="Question owner accepted this answer as best answer" class=" mt-2">
                                    <i class="fas fa-check fa-2x"></i>
                                </a>
                            {% endif %}
                        </div>
                        <div class="media-body">
                            {{ answer.body | safe }}

                            <div class="row">

                                <div class="col-4">
                                    <div class="ml-auto" style="margin-top: 10px">
                                        {% if answer.user.id == request.user.id %}
                                            <a href="#" class="btn btn-sm btn-outline-info">Edit</a>
                                            <form class="form-delete" method="post"
                                                  action="">
                                                {% csrf_token %}
                                                <button type="button" class="btn btn-sm btn-outline-danger"
                                                        onclick="return confirm('Are you sure?')">Delete
                                                </button>
                                            </form>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-4"></div>
                                <div class="col-4">
                                    <span class="text-muted">Answered by {{ answer.created_at|timesince }} ago</span>
                                    <div class="media mt-2">
                                        <a href="" class="pr-2">
                                            <img src="{{ "https://www.gravatar.com/avatar/{}?s=32" }}">
                                        </a>
                                        <div class="media-body mt-1">
                                            <a href="">{{ answer.user.username }}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>