qa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

from qaapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('qaapp.urls', namespace='qa')),
]

handler404 = views.handler404

qaapp/urls.py
from django.urls import path

from qaapp.views import QuestionDetailsView
from . import views

app_name = 'qa'

urlpatterns = [
    path('', views.QuestionListView.as_view(), name='home'),
    path('questions/<slug:slug>/', QuestionDetailsView.as_view(), name='questions-detail'),
    path('questions/create', views.QuestionCreateView.as_view(), name='questions-create'),
    path('questions/<slug:slug>/edit', views.QuestionUpdateView.as_view(), name='questions-edit'),
    path('questions/<slug:slug>/delete', views.QuestionDestroyView.as_view(), name='questions-delete'),
    path('questions/<int:question_id>/<str:flag>', views.question_vote, name='questions-vote'),
    # answer
    path('answers/<int:question_id>/<int:answer_id>/best_answer', views.mark_as_best, name='mark-as-best'),
]

templates/questions/create.html
{% extends 'base.html' %}

{% block title %} {{ title }}{{ block.super }}{% endblock title %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h2>Ask Question</h2>
                            <div class="ml-auto">
                                <a href="{% url 'qa:home' %}" class="btn btn-outline-secondary">Back to all
                                    Questions</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <form action="" method="post">
                            {% include "questions/form.html" with text="Ask Question" %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/questions/edit.html
{% extends 'base.html' %}

{% block title %} {{ title }}{{ block.super }}{% endblock title %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h2>Edit your question</h2>
                            <div class="ml-auto">
                                <a href="{% url 'qa:home' %}" class="btn btn-outline-secondary">
                                    Back to all Questions</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <form action="" method="post">
                            {% include "questions/form.html" with text="Update Question" %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/questions/excerpt.html
<div class="media post">
    <div class="d-flex flex-column counters">
        <div class="vote">
            <strong>{{ question.question_votes.count }}</strong> Votes
        </div>
        <div class="status {% if question.answer.count %}answered{% endif %}">
            <strong>{{ question.answer.count }}</strong> Answers
        </div>
        <div class="view">
            0 Views
        </div>
    </div>
    <div class="media-body">
        <div class="d-flex align-items-center">
            <h3 class="mt-0">
                <a href="{% url 'qa:questions-detail' question.slug %}">{{ question.title }}</a>
            </h3>
            <div class="ml-auto">
                {% if request.user.is_authenticated and question.user.id == request.user.id %}
                    <a href="{% url 'qa:questions-edit' question.slug %}" class="btn btn-sm btn-outline-info">Edit</a>
                    <form class="form-delete" method="post" action="{% url 'qa:questions-delete' question.slug %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-outline-danger"
                                onclick="return confirm('Are you sure?')">Delete
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
        <p class="lead">
            Asked by {{ question.user.username }}
            <a href=""></a>
            <small class="text-muted"></small>
        </p>
    </div>
</div>

templates/questions/form.html
{% csrf_token %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

{% for field in form %}
    <div class="form-group">
        <label for="id_{{ field.name }}">{{ field.label }}</label>
        {% if field.name != 'body' %}
            <input type="{{ field.field.widget.input_type }}"
                   class="form-control"
                   name="{{ field.name }}"
                   id="id_{{ field.name }}"
                   value="{{ field.value }}"
                   required
                   placeholder="{{ field.field.widget.attrs.placeholder }}">
        {% else %}
            {{ field }}
        {% endif %}
    </div>
{% endfor %}
<div class="form-group">
    <button type="submit" class="btn btn-outline-primary btn-lg">{{ text }}</button>
</div>

templates/questions/show.html
{% extends 'base.html' %}

{% block title %} {{ title }}{{ block.super }}{% endblock title %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <div class="d-flex align-items-center">
                                <h1>{{ question.title }}</h1>
                                <div class="ml-auto">
                                    <a href="{% url 'qa:home' %}" class="btn btn-outline-secondary">
                                        Back to all Questions</a>
                                </div>
                            </div>
                        </div>

                        <hr>

                        <div class="media">
                            <div class="d-fex flex-column vote-controls">
                                {#                                {{ vote_type }}#}
                                {#  {% if request.user.question_votes.get(question=question) %} {% endif %}#}
                                <a title="This question is useful"
                                   class="vote-up {% if request.user.is_authenticated and voted and vote_type == 'upvote' %}''{% else %}off{% endif %}"
                                   onclick="event.preventDefault(); document.getElementById('up-vote-question-{{ question.id }}').submit();">
                                    <i class="fas fa-caret-up fa-3x"></i>
                                </a>
                                <form id="up-vote-question-{{ question.id }}"
                                      action="/questions/{{ question.id }}/upvote" method="POST" style="display:none;">
                                    {% csrf_token %}
                                    <input type="hidden" name="vote" value="1">
                                    <input type="hidden" name="type" value="downvote">
                                </form>

                                {% if votes_count.vote__sum > 0 %}
                                    <span class="votes-count">{{ votes_count.vote__sum }}</span>
                                {% else %}
                                    <span class="votes-count">0</span>
                                {% endif %}

                                <a title="This question is not useful"
                                   class="vote-down {% if request.user.is_authenticated and voted and vote_type == 'downvote' %}''{% else %}off{% endif %}"
                                   onclick="event.preventDefault(); document.getElementById('down-vote-question-{{ question.id }}').submit();">
                                    <i class="fas fa-caret-down fa-3x"></i>
                                </a>
                                <form id="down-vote-question-{{ question.id }}"
                                      action="/questions/{{ question.id }}/downvote" method="POST"
                                      style="display:none;">
                                    {% csrf_token %}
                                    <input type="hidden" name="vote" value="-1">
                                    <input type="hidden" name="type" value="downvote">
                                </form>

                                <a title="Click to mark as favorite question (Click again to undo)"
                                   class="favorite mt-2 favorited">
                                    <i class="fas fa-star fa-2x"></i>
                                    <span class="favorites-count">1</span>
                                </a>
                            </div>
                            <div class="media-body">
                                {{ question.body }}
                                <div class="clearfix"></div>
                                {% if request.user == question.user %}
                                    <a href="{% url 'qa:questions-edit' question.slug %}"
                                       class="btn btn-sm btn-outline-info">Edit</a>
                                {% endif %}
                                <div class="float-right">
                                    <span class="text-muted">Asked By {{ question.created_at|timesince }} ago</span>
                                    <div class="media mt-2">
                                        <a href="" class="pr-2">
                                            <img src="{{ "https://www.gravatar.com/avatar/{}?s=32" }}">
                                        </a>
                                        <div class="media-body mt-1">
                                            <a href="">{{ question.user.username }}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% include 'answers/_index.html' with answers=question.answer.all %}
        {% include 'answers/_create.html' %}
    </div>

{% endblock %}