accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.Login.as_view(), name='login'),
    # path('login', views.login, name='login'),
    path('register', views.Register.as_view(), name='register'),
    path('logout', views.LogoutView.as_view(), name='logout'),
]

qa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

from qaapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('qaapp.urls', namespace='qa')),
]

handler404 = views.handler404

qaapp/urls.py
from django.urls import path

from qaapp.views import QuestionDetailsView
from . import views

app_name = 'qa'

urlpatterns = [
    path('', views.QuestionListView.as_view(), name='home'),
    path('questions/<slug:slug>/', QuestionDetailsView.as_view(), name='questions-detail'),
    path('questions/create', views.QuestionCreateView.as_view(), name='questions-create'),
    path('questions/<slug:slug>/edit', views.QuestionUpdateView.as_view(), name='questions-edit'),
    path('questions/<slug:slug>/delete', views.QuestionDestroyView.as_view(), name='questions-delete'),
    path('questions/<int:question_id>/<str:flag>', views.question_vote, name='questions-vote'),
    # answer
    path('answers/<int:question_id>/<int:answer_id>/best_answer', views.mark_as_best, name='mark-as-best'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <title>QA | {% block title %}{% endblock %}</title>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{% url 'qa:home' %}">
                QA
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    {% if user and user.is_anonymous %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ request.user.username }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                                    Logout
                                </a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        {% block content %}
        {% endblock %}
    </main>
</div>

<script src="{% static 'js/app.js' %}"></script>
{#<script src="{% static 'js/jquery-2.2.3.js' %}"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>#}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %} {{ title }}{{ block.super }}{% endblock title %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h2>All Questions</h2>
                            <div class="ml-auto">
                                <a href="{% url 'qa:questions-create' %}" class="btn btn-outline-secondary">Ask
                                    Question</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        {#@include ('layouts._messages')#}

                        {% if questions %}

                            {% for question in questions %}
                                {% include 'questions/excerpt.html' %}
                            {% endfor %}

                        {% else %}
                            <div class="alert alert-warning">
                                <strong>Sorry</strong> There are no questions available.
                            </div>
                        {% endif %}

                        <div class="row justify-content-center" style="margin-top: 20px">
                            {% if is_paginated %}
                                <nav>
                                    <ul class="pagination">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                                        {% endif %}
                                        {% for i in page_obj.paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class="page-item active">
                                                    <a class="page-link" href="#">
                                                        {{ i }} <span class="sr-only">(current)</span>
                                                    </a>
                                                </li>
                                            {% else %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if page_obj.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled"><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}